version: '3.9'

services:

  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_DB: inventario
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@correo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db

  app:
    build: . # Permite construir la imagen con docker-compose up --build localmente
    image: ghcr.io/Michaeldlt1/devops-flask-postgres:2.0.0 
    container_name: flaskapp
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=Sistema de Inventario DevOps
      - APP_VERSION=2.0.0
      - DB_HOST=db
      - DB_NAME=empresa
      - DB_USER=admin
      - DB_PASSWORD=admin123
    depends_on:
      - db

volumes:
  postgres_data: